const mongoose = require("mongoose");

const EventModel = new mongoose.Schema(
  //id generated by mongo
  {
    title: { type: String, required: true, trim: true },
    type: {
      type: String,
      enum: ["poetry_night", "book_club", "signing"],
      required: true,
    },
    date: { type: Date, required: Date },
    description: { type: String, required: true },
    capacity: {
      type: Number,
      required: true,
      min: 1,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Event", EventSchema);
